sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
  - 3.5
install:
  - pip install -r requirements.txt
script:
  - python convertToHtml.py -t "Test Report" -i testresults.json -c dark-style.css -o results.html
